### ISSUE TITLE
Getting "error: option `push-option' requires a value"

### ISSUE THREAD

**Issue by dabeeeenster** [IlyaSemenov/gitlab-ci-git-push#4]
This container was working fine but I think the recent commit has broken things for me. The gitlab-ci.yml file reads

```
deploytostaging:
    image: ilyasemenov/gitlab-ci-git-push
    stage: deploy
    script: git-push dokku@<my dokku server>:admin-staging
    only:
        - develop
```

but I get this error on build:

```
error: option `push-option' requires a value
usage: git push [<options>] [<repository> [<refspec>...]]
```
